version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: bookmarkdb
      MYSQL_USER: bookmark
      MYSQL_PASSWORD: bookmark
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
