version: '3'

services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d # 初期化SQLのファイルをマウント
    environment:
      MYSQL_DATABASE: bookmarkdb
      MYSQL_USER: bookmark
      MYSQL_PASSWORD: bookmark
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"